### ISSUE TITLE
Invalid testnet mock configs

### ISSUE THREAD

**Issue by dbejarano820** [keep-starknet-strange/gomu-gomu-no-gatling#10]
After the merge of https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/pull/3

The only functional configs are `default.yaml` and `2.1.0.yaml`.

- devnet
- rinnegan (not sure of the status of this one)
- sharingan
- testnet

are all outdated and still contain the simulation config.

The readme is suggesting to run `gatling shoot -c config/rinnegan.yaml` which evidently fails.

**Comment by dbejarano820** [comment]
@d-roak 
I can take it on, should they be using 2.1.0 contracts?

**Comment by d-roak** [comment]
devnet - we can rm this
testnet - I'll refactor this file
@abdelhamidbakhta what are the madara versions on rinnegan and sharingan?
