### ISSUE TITLE
Create an action to run on GH Actions

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/gomu-gomu-no-gatling#6]
## Description
We should be able to run gomu gomu no gatling in GH workflows. 

## Requirements
- Able to run benchmark as an official action
- Set the configuration file within the main repository
- Set all remaining flags on the binary as configs

## References
https://docs.github.com/en/actions/creating-actions

**Comment by dbejarano820** [comment]
I'd love to take this one on! Good opportunity to learn about GitHub actions

**Comment by d-roak** [comment]
Go ahead, lmk if you need any help with it!

**Comment by d-roak** [comment]
completed at #11
