### ISSUE TITLE
Redefine behaviour for `num_accounts`

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/gomu-gomu-no-gatling#9]
## Context
Currently the `num_accounts` is the number of accounts that are receiving transactions. It's counterintuitive, looking at first sight, we expect it to be the number of accounts that are sending transactions.

https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/blob/88f02ca756aa212ccba81fb7d80f4775fc7d34bc/config/default.yaml#L15

## Description
- Add the possibility to send transactions from multiple accounts
- Rethink if we need to define the number of receiving accounts (what is the use case we want to benchmark)

**Comment by EvolveArt** [comment]
I'll take this one

**Comment by d-roak** [comment]
closed on #23
